em

em usos
 empurrar:
 ramos: ["diretor"]
 fluxo de trabalho_despacho:

permissões:
 conteúdo: ler
 páginas: escrivão
 token de identificação: escrivão

simultaneidade:
 grupo: "páginas"
 cancelamento em andamento: verdadeiro

empregadores:
 construir:
 continua correndo: ubuntu-mais recente
 etapas:
      - nome: Finalizar compra
 usos: nomeações/checkout@v4

ações/checkout@v4nome:   usossosConfigurar não
 usos:  c com
comunicações/setup-node@v4nome
 versão do nó: 20
 cache: nomepm

nome npm:    corretorcorretorcorretorInstalar
 corretor: nomepm ci

npm cinome:    corretororretorcorretorConstruir
 corretor: nomepm executar compilação

npm executar compilação:  usosCarregar artefato
nome:  comasomasomasões/upload-pages-artifact@v3
 com:
 caminho: dist

 implantar:
 continua correndo: ubuntu-mais recente
 necessidades: construir
 etapas:
      - nome: Implantar em páginas
 usos: ações/deploy-pages@v4
